import { Request, Response } from 'express';
export declare function listUsers(req: Request, res: Response): Promise<void>;
export declare function getUserTransactions(req: Request, res: Response): Promise<void>;
export declare function listTransactions(req: Request, res: Response): Promise<void>;
export declare function getFlow(_req: Request, res: Response): Promise<void>;
export declare function listReportLogs(req: Request, res: Response): Promise<void>;
export declare function downloadReport(req: Request, res: Response): Promise<void>;
export declare function generateReport(req: Request, res: Response): Promise<void>;
export declare function updateFlow(req: Request, res: Response): Promise<void>;
export declare function getUserSubscription(req: Request, res: Response): Promise<void>;
export declare function updateUserSubscription(req: Request, res: Response): Promise<void>;
